# Generated by Django 2.0 on 2018-01-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_roles',
        ),
        migrations.AlterField(
            model_name='user_role',
            name='user',
            field=models.ForeignKey(on_delete=None, to='rbac.MyUserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='myuserinfo',
            name='user_roles',
            field=models.ManyToManyField(through='rbac.User_Role', to='rbac.Role'),
        ),
    ]
