# Generated by Django 2.0 on 2018-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180119_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerGroup',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='power',
            name='code',
            field=models.CharField(default='add', max_length=32, verbose_name='权限代号'),
        ),
        migrations.AddField(
            model_name='power',
            name='group',
            field=models.ForeignKey(default=1, on_delete=None, to='rbac.PowerGroup', verbose_name='权限组'),
        ),
    ]
