# Generated by Django 2.0 on 2018-01-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20180119_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='power',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=None, to='rbac.Power', verbose_name='可以作为菜单显示的权限'),
        ),
        migrations.AddField(
            model_name='powergroup',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=None, to='rbac.Menu', verbose_name='菜单'),
        ),
    ]
